project:
  type: website

website:
  page-navigation: true
  title: "STA 240 Fall 2026"
  description: "Homepage for STA 240 Probability for Statistical Inference at Duke University (Fall 2026)"
  site-url: "https://sta240-f26.github.io/"

  open-graph: true

  sidebar:
    background: "#FF2400"
    logo: "img/logo.png"
    pinned: true
    align: center
    tools:
      - icon: code-square
        href: https://cmgr.oit.duke.edu/containers
        text: "RStudio Containers"
      - icon: megaphone
        href: https://canvas.duke.edu/courses/84105
        text: "Canvas"
      - icon: people
        href: https://edstem.org/us/courses/96707/discussion
        text: "Ed Discussion"
      - icon: file-arrow-up
        href: https://www.gradescope.com/courses/1351871
        text: "Gradescope"

    style: docked
    search: true
    collapse-level: 1
    contents:
      - href: syllabus/announcements.qmd
        text: Check it out!
      - section: "Syllabus"
        contents:
          - href: syllabus/syllabus-overview.qmd
            text: Overview
          - href: syllabus/syllabus-team.qmd
            text: Teaching team
          - href: syllabus/syllabus-materials.qmd
            text: Materials
          - href: syllabus/syllabus-assignments.qmd
            text: Assignments and grading
          - href: syllabus/syllabus-policies.qmd
            text: Policies
          - href: syllabus/syllabus-resources.qmd
            text: University resources
          - href: index.qmd
            text: Schedule
      - section: "Math Helpers"
        contents:
          - href: math/greeks.qmd
            text: Greek alphabet
          - href: math/logexp.qmd
            text: Exponents and logarithms
          - href: math/differentiation.qmd
            text: Differentiation
          - href: math/integration.qmd
            text: Integration
          - href: math/limits.qmd
            text: Limits and continuity
          - href: math/series.qmd
            text: Sequences and series
          - href: math/gamma-function.qmd
            text: Gamma function
          #- href: math/massage-and-squint.qmd
          #  text: Massage and squint
      - section: "Code Helpers"
        contents:
          - href: explainers/setup.qmd
            text: Getting started
          - href: explainers/hello-rstudio.qmd
            text: The lay of the land
          - href: explainers/quarto.qmd
            text: Quarto
          - href: explainers/latex.qmd
            text: Typing math
          - href: explainers/math.qmd
            text: Basic math
          - href: explainers/vectors.qmd
            text: Vectors
          - href: explainers/lineplot.qmd
            text: Plotting lines
          - href: explainers/sample.qmd
            text: sample
          - href: explainers/if-else.qmd
            text: if-else and logic
          - href: explainers/loops.qmd
            text: for loops
          - href: explainers/vectorization.qmd
            text: Vectorization
          - href: explainers/rng-seed.qmd
            text: Setting a seed
          - href: explainers/probabilities.qmd
            text: Computing probabilities
          - href: explainers/plot.qmd
            text: Plotting points
          - href: explainers/summary-statistics.qmd
            text: Summary statistics
          - href: explainers/histogram.qmd
            text: Histograms
      - section: "Distributions"
        contents:
          - href: distributions/discrete-binomial.qmd
            text: Binomial
          - href: distributions/discrete-geometric.qmd
            text: Geometric
          - href: distributions/discrete-poisson.qmd
            text: Poisson
      - section: "Problem Sets"
        contents:
          - href: problems/pset-0.qmd
            text: Problem Set 0
          - href: problems/pset-1.qmd
            text: Problem Set 1
          - href: problems/pset-2.qmd
            text: Problem Set 2
          - href: problems/pset-3.qmd
            text: Problem Set 3
      - section: "Labs"
        contents:
          - href: lab/lab-1.qmd
            text: Lab 1
          - href: lab/lab-2.qmd
            text: Lab 2
          - href: lab/lab-3.qmd
            text: Lab 3
            
  page-footer:
    right: 'This page is built with [Quarto](https://quarto.org/).'
    left: "&copy; Copyright 2026 John Zito"
    background: "#FF2400"

format: 
  html:
    mainfont: Atkinson Hyperlegible
    highlight-style: a11y-light

theme:
  light: [cosmo, style/sta199.scss]
#  dark: [cosmo, style/sta199.scss, style/dark.scss]
linkcolor: "#798b93"
toc: true
code-copy: hover
code-link: true
code-overflow: wrap

execute:
  freeze: auto
  
