Here is a list of events that may or may not happen, but I believe we will know the final outcome before the end of the semester:

- The Democratic Party takes control of the US House of Representatives after the midterm elections;
- The Democratic Party takes control of the US Senate after the midterm elections;
- The [global price of Brent crude oil](https://www.nytimes.com/2026/09/09/business/brent-oil-100-barrel-iran-war.html?unlocked_article_code=1.BFE.BwNU.1uLTtDdcVc7H&smid=url-share) is below $100 on Wednesday December 2 (our last lecture);
-   *The Hunger Games: Sunrise on the Reaping* makes more money at the US domestic box office (inflation adjusted) on its opening weekend than *The Hunger Games: The Ballad of Songbirds & Snakes*;
- The LA Dodgers appear in the 2026 World Series;
- Robert Barro is awarded a 2026 Nobel Prize in economic sciences;
- A student recommendation appears in JZ's end-of-year Spotify Top ~~100~~ 10;
- The police are called to Waynestock in October.

Based on these, please do the following:

a. For each event, state the probability that you personally assign to the event happening;
a. Pick **three** of the events and write a paragraph for each explaining how you formulated your beliefs. What reasoning and evidence did you consider, and how did you weigh it? Feel free to provide links to online sources as needed.

::: callout-tip
## Avoid wishful thinking

For some of these, you may have strong preferences about the outcome. Try to set them aside and report your honest assessment of the likelihood of the event, whether it pleases you or not.
:::
