Here are some short readings about [the case of Sally Clark and Roy Meadow](/slides/2026-08-24-welcome.html#/sally-clark-1964---2007), as well as something called the *prosecutor's fallacy*:

- Grimes (2023): "[Bad Science and Bad Statistics in the Courtroom Convict Innocent People](/readings/grimes-2023-sciam.pdf)," *Scientific American*;
- Carriquiry (2018): "[Misuse of statistics in the courtroom: the Sally Clark case](https://forensicstats.org/blog/misuse-of-statistics-in-the-courtroom-the-sally-clark-case)," CSAFE;
- Westreich & Iliinsky (2014): "[Epidemiology visualized: the prosecutor's fallacy](/readings/westreich-iliinsky-2014-aje.pdf)," *American Journal of Epidemiology*;
- [AP Dawid](https://en.wikipedia.org/wiki/Philip_Dawid)'s [statement](/readings/dawid-clark-statement.pdf) during the Clark appeal.

Please do the following:

a. Read the articles;
b. Using the ideas of conditional probability and independence that we have studied, write a paragraph or two describing what the prosecutor's fallacy is and how it applies to the Clark case;
c. If you were an attorney for the defense and had the chance to cross-examine Roy Meadow, what would you ask him about his statistical testimony? What are the most incisive questions you could ask? How would you ensure that the cross-examination would "land" with the members of the jury, who most likely know absolutely nothing about probability and statistics?

::: callout-warning
## Please don't break my heart

I'm not asking you to read *Moby-Dick* here.
:::



