---
title: "Assignments and grading"
editor: 
  mode: source
---

Your final course grade will be calculated as follows:

::: {.center-table}
| Category       | Percentage |
|----------------|------------|
| Labs           | 10%        |
| Problem Sets   | 20%        |
| Midterm Exam 1 | 20%        |
| Midterm Exam 2 | 20%        |
| Final exam     | 30%        |
:::

Your final letter grade will be determined based on the usual thresholds:

::: {.center-table}
| Letter Grade | Final Course Grade |
|--------------|--------------------|
| A            | \>= 93             |
| A-           | 90 - 92.99         |
| B+           | 87 - 89.99         |
| B            | 83 - 86.99         |
| B-           | 80 - 82.99         |
| C+           | 77 - 79.99         |
| C            | 73 - 76.99         |
| C-           | 70 - 72.99         |
| D+           | 67 - 69.99         |
| D            | 63 - 66.99         |
| D-           | 60 - 62.99         |
| F            | \< 60              |
:::

::: callout-warning
These thresholds will not change, and they will be applied exactly. This means that the final grades will not be curved, and a 92.99, for example, will not be rounded up to an A.
:::

## Labs (10%)

In your lab section each Thursday, you will get into randomly assigned groups and complete a guided activity that shows you how computer simulation complements the mathematics we are studying. We will implement these simulations using the base functionality of the `R` programming language. Your lab write-up is due at the end of your lab section, and late work will not be accepted. 

::: callout-note
## Grace

Your two lowest lab scores will be dropped at the end of the semester. 
:::


## Problem Sets (20%)

Mathematics is like everything else in life; if you practice, you improve. As such, the problem sets are really the heart of the course. They will mostly consist of pencil-and-paper math problems, but you will also practice the coding skills developed in lab. You may compose your solutions however you like (scan or photograph written work, LaTeX, Quarto, handwriting capture on a tablet, whatever) so long as you ultimately upload a single `.pdf` file to Gradescope.

::: callout-note
## Grace

Your lowest problem set score will be dropped at the end of the semester.
:::

## Exams (70%)

There will be three exams. The dates and times are firm, so mark your calendar now:

-   **Midterm 1** (20%): Thursday October 8 during your lab;
-   **Midterm 2** (20%): Thursday November 12 during your lab;
-   **Final** (30%): Monday December 14 from 2pm to 5pm Location TBD.

These will be old school, pencil-and-paper, in-class exams. The only resource you are allowed is both sides of one 8.5" x 11" sheet of notes, prepared by you and you alone. You can create it however you wish: handwritten, on a computer, on a tablet device, etc.

If you seek testing accommodations, make sure the Student Disability Access Office sends me a letter, and then please make your appointments in the [Testing Center](https://testingcenter.duke.edu) as soon as possible.

::: callout-note
## Grace

If you do better on the final exam than you did on one of the midterms, we will replace your lowest midterm exam score with your final exam score.
:::

::: callout-warning
## No make-up exams

If you are absent from one of the midterms for whatever reason, there will not be a make-up. Pursuant to the above policy, we will simply replace the missed midterm score with the final exam score. If you miss the final exam, you get a zero unless you have a [Dean's Excuse](https://trinity.duke.edu/undergraduate/academic-policies/final-exams-scheduling-conflicts-and-absences).
:::
