---
title: "Assignments and grading"
editor: 
  mode: source
---

Your final course grade will be calculated as follows:

::: {.center-table}
| Category       | Percentage |
|----------------|------------|
| Labs           | 10%        |
| Problem Sets   | 30%        |
| Midterm Exam 1 | 20%        |
| Midterm Exam 2 | 20%        |
| Final exam     | 20%        |
:::

Your final letter grade will be determined based on the usual thresholds:

::: {.center-table}
| Letter Grade | Final Course Grade |
|--------------|--------------------|
| A            | \>= 93             |
| A-           | 90 - 92.99         |
| B+           | 87 - 89.99         |
| B            | 83 - 86.99         |
| B-           | 80 - 82.99         |
| C+           | 77 - 79.99         |
| C            | 73 - 76.99         |
| C-           | 70 - 72.99         |
| D+           | 67 - 69.99         |
| D            | 63 - 66.99         |
| D-           | 60 - 62.99         |
| F            | \< 60              |
:::

::: callout-warning
These thresholds will not change, and they will be applied exactly. This means that the final grades will not be curved, and a 92.99, for example, will not be rounded up to an A.
:::

## Labs (10%)

In lab every Thursday, you will complete a guided activity that introduces you to special topics, extensions, or applications of the latest course material. Along the way, we will teach you how to implement some of the ideas from the course in the `R` programming language. Ideally you should be able to finish the activity by the end of your lab period, but in any case, you must submit your lab work by 11:59 ET PM that same day.

Each lab assignment will be graded on the following scale:

-   1.0: a complete, good faith attempt at every part of every problem;
-   0.5: partially complete;
-   0.0: no submission, or mostly incomplete.

::: callout-note
## Grace

Your two lowest lab scores will be dropped at the end of the semester.
:::

## Problem Sets (30%)

Mathematics is like everything else in life; if you practice, you improve. As such, the problem sets are really the heart of the course. They will mostly consist of pencil-and-paper math problems, but sometimes you will be asked to do some coding. You may compose you solutions however you like (scan or photograph written work, LaTeX, Quarto, handwriting capture on a tablet, whatever) so long as you ultimately upload a single `.pdf` file to Gradescope.

::: callout-note
## Grace

Your lowest problem set score will be dropped at the end of the semester.
:::

## Exams (20% each)

There will be three exams. The dates, times, and locations are firm, so mark your calendar now:

-   **Midterm 1**: Thursday October 9 during your lab;
-   **Midterm 2**: Thursday November 13 during your lab;
-   **Final**: Friday December 12 from 9 AM - 12 PM in Old Chem 116.

These will be old school, pencil-and-paper, in-class exams. You are allowed only two resources:

- a "dumb" calculator (no wi-fi). You will not actually need it, but if you want it as a security blanket, be my guest;
- both sides of one 8.5" x 11" sheet of notes, prepared by you and you alone. You can create it however you wish: handwritten, on a computer, etc.

If you seek testing accommodations, make sure the Student Disability Access Office sends me a letter, and then please make your appointments in the [Testing Center](https://testingcenter.duke.edu) as soon as possible.

::: callout-note
## Grace

If you do better on the final exam than you did on one of the midterms, we will replace your lowest midterm exam score with your final exam score.
:::

::: callout-warning
## No make-up exams

If you are absent from one of the midterms for whatever reason, there will not be a make-up. Pursuant to the above policy, we will simply replace the missed midterm score with the final exam score. If you miss the final exam, you get a zero unless you have a [Dean's Excuse](https://trinity.duke.edu/undergraduate/academic-policies/final-exams-scheduling-conflicts-and-absences).
:::
