---
title: "Poisson distribution"
format: html
filters:
  - shinylive
---

The Poisson distribution is what you get when you send the number of trials in the binomial distribution to infinity. This distribution is useful for modeling the number of random arrivals in a given window of time: 

- how many claims an insurance company receives in a month;
- how many emails you receive in an hour;
- how many "likes" you receive on a dating app in a day.

The distribution is governed by one parameter $\lambda>0$ which is called the **rate**.

## Basic properties

|  |        |
|------|--------------------|
| **Notation** | $X\sim\text{Poisson}(\lambda)$  |
| **Range** | $\mathbb{N}=\{0,\,1,\,2,\,3,\,4,\,...\}$ |
| **Parameter space** | $\lambda>0$ |
| **PMF** | $P(X=k)=e^{-\lambda}\frac{\lambda^k}{k!}$ |
| **Expectation** | $\lambda$ |
| **Variance** | $\lambda$ |

## `R` commands

[Here](https://stat.ethz.ch/R-manual/R-devel/library/stats/html/Poisson.html) is the documentation for the suite of commands that let you work with the Poisson distribution in `R`:

```{r}
#| eval: false
dpois(x, lambda) # PMF: P(X = x)
ppois(q, lambda) # CDF: F(q) = P(X <= q)
qpois(p, lambda) # quantile function (inverse CDF)
rpois(n, lambda) # random numbers
```

## Play around!

As $\lambda$ grows, the distribution shifts to the right and gets wider, which makes sense since $\lambda$ acts as both the mean and variance:


```{shinylive-r}
#| standalone: true
#| viewerHeight: 500

library(shiny)

discrete_pmf <- function(x, p, xlim = c(min(x) - 1, max(x) + 1), label = "", add_mean = FALSE){
  plot(x, p,
       pch = 19,
       cex = 0.5,
       xlab = "",
       ylab = "",
       main = "",
       ylim = c(0, 0.4),
       yaxs = "i",
       yaxt = "n",
       xlim = xlim,
       xaxt = "n",
       bty = "n"
  )
  segments(x,
           rep(0, length(x) + 1),
           x1 = x,
           y1 = p,
           lwd = 3
  )
  axis(1, at = floor(xlim[1]):ceiling(xlim[2]), cex.axis = 1)
  axis(2, at = seq(0, 1, length.out = 11), las = 1, cex.axis = 1.5)
  legend("topright", label, bty = "n", cex = 3)
  if(add_mean == TRUE){
    mtext("E(X)", side = 1, at = sum(x * p), col = "red", line = 2)
  }
}

discrete_cdf <- function(x, p, xlim = c(min(x) - 1, max(x) + 1), label = ""){
  closeddot = cumsum(p)
  opencircle = c(0, closeddot[1:length(x)-1])
  plot(x, closeddot, pch = 19, cex = 0.5,
       ylim = c(0, 1),
       ylab = "", main = "", xlab = "",
       yaxt = "n",
       xlim = xlim,
       xaxt = "n",
       #yaxs = "i", 
       bty = "n")
  points(x, opencircle, cex = 0.5)
  segments(c(xlim[1], x), c(0, closeddot), c(x, xlim[2]), c(0, closeddot), lwd = 1)
  axis(1, at = floor(xlim[1]):ceiling(xlim[2]), cex.axis = 1)
  axis(2, at = seq(0, 1, length.out = 11), las = 1, cex.axis = 1.5)
  legend("bottomright", label, bty = "n", cex = 3)
}

# Define UI for application that draws a histogram
ui <- fluidPage(
  
  # Application title
  titlePanel("Poisson distribution CDF and PMF"),
  
  # Sidebar with a slider input for number of bins 
  sidebarLayout(
    sidebarPanel(
      sliderInput("lambda",
                  "Rate (λ):",
                  min = 0,
                  max = 100,
                  value = 1,
                  step = 0.1)
    ),
    
    # Show a plot of the generated distribution
    mainPanel(
      plotOutput("distPlot")
    )
  )
)

# Define server logic required to draw a histogram
server <- function(input, output) {
  
  output$distPlot <- renderPlot({
    
    lambda <- input$lambda
    n <- 100

    par(mfrow = c(2, 1), mar = c(4, 4, 2, 2))
    
    discrete_cdf(0:n, dpois(0:n, lambda))
    discrete_pmf(0:n, dpois(0:n, lambda), add_mean = FALSE)
    mtext("E(X)", side = 1, at = lambda, col = "red", line = 2)
  })
}

# Run the application 
shinyApp(ui = ui, server = server)
```

::: callout-important
## Magic is happening!

Notice that the shape of the PMF becomes more like the bell curve as $\lambda$ grows. This is not an accident. It is a consequence of a deep result known as **the central limit theorem**.
:::

## Derivations

::: {.callout-note collapse="true"}
## Connecting the binomial and the Poisson

Fix $\lambda>0$ and consider $X\sim\text{Binom}(n,\,\lambda / n)$. Then for any $k\leq n$, we have 

$$
\begin{aligned}
P(X=k)
&=
\binom{n}{k}
\left(\frac{\lambda}{n}\right)^k
\left(1-\frac{\lambda}{n}\right)^{n-k}
\\
&=
\binom{n}{k}
\frac{\lambda^k}{n^k}
\left(1-\frac{\lambda}{n}\right)^{n-k}
\\
&=
\binom{n}{k}
\frac{\lambda^k}{n^k}
\left(1-\frac{\lambda}{n}\right)^{n}
\left(1-\frac{\lambda}{n}\right)^{-k}
\\
&=
\frac{n!}{k!(n-k)!}
\frac{\lambda^k}{n^k}
\left(1-\frac{\lambda}{n}\right)^{n}
\left(1-\frac{\lambda}{n}\right)^{-k}
\\
&=
\frac{\lambda^k}{k!}
\left(1-\frac{\lambda}{n}\right)^{n}
\frac{n!}{n^k(n-k)!}
\left(1-\frac{\lambda}{n}\right)^{-k}
\\
&=
\frac{\lambda^k}{k!}
\left(1-\frac{\lambda}{n}\right)^{n}
\frac{n(n-1)(n-2)\cdots(n-k+1)}{n^k}
\left(1-\frac{\lambda}{n}\right)^{-k}
\\
&=
\frac{\lambda^k}{k!}
\left(1-\frac{\lambda}{n}\right)^{n}
\frac{n(n-1)(n-2)\cdots(n-k+1)}{n\times n\times n\times\cdots\times n}
\left(1-\frac{\lambda}{n}\right)^{-k}
\\
&=
\frac{\lambda^k}{k!}
\left(1-\frac{\lambda}{n}\right)^{n}
\left(\frac{n}{n}\right)\left(\frac{n-1}{n}\right)\left(\frac{n-2}{n}\right)\cdots \left(\frac{n-k+1}{n}\right)
\left(1-\frac{\lambda}{n}\right)^{-k}
\\
&=
\frac{\lambda^k}{k!}
\left(1-\frac{\lambda}{n}\right)^{n}
(1)\left(1-\frac{1}{n}\right)\left(1-\frac{2}{n}\right)\cdots \left(1-\frac{k-1}{n}\right)
\left(1-\frac{\lambda}{n}\right)^{-k}
.
\end{aligned}
$$

Take the limit as $n\to\infty$ and you get

$$
\begin{aligned}
\lim_{n\to\infty}
P(X=k)
&=
\lim_{n\to\infty}
\frac{\lambda^k}{k!}
\left(1-\frac{\lambda}{n}\right)^{n}
\left(1-\frac{1}{n}\right)\left(1-\frac{2}{n}\right)\cdots \left(1-\frac{k-1}{n}\right)
\left(1-\frac{\lambda}{n}\right)^{-k}
\\
&=
\frac{\lambda^k}{k!}
\lim_{n\to\infty}
\left(1-\frac{\lambda}{n}\right)^{n}
\left(1-\frac{1}{n}\right)\left(1-\frac{2}{n}\right)\cdots \left(1-\frac{k-1}{n}\right)
\left(1-\frac{\lambda}{n}\right)^{-k}
\\
&=
\frac{\lambda^k}{k!}
\underbrace{\lim_{n\to\infty}
\left(1-\frac{\lambda}{n}\right)^{n}}_{e^{-\lambda}}
\times \underbrace{\lim_{n\to\infty}
\left(1-\frac{1}{n}\right)}_{1}
\times \underbrace{\lim_{n\to\infty}\left(1-\frac{2}{n}\right)}_{1}\cdots 
\times \underbrace{\lim_{n\to\infty}\left(1-\frac{k-1}{n}\right)}_{1}
\times \underbrace{\lim_{n\to\infty}\left(1-\frac{\lambda}{n}\right)^{-k}}_{1}.
\\
&=
\frac{\lambda^k}{k!}
e^{-\lambda}.
\end{aligned}
$$

We used the fact that "[the limit of a product is the product of the limits](/math/series.html#limit-rules)" (provided the separate limits exist and are finite, which they all are here), and we needed to recall the *definition* of the [exponential function](/math/logexp.html):

$$
e^x=\lim_{n\to\infty}\left(1+\frac{x}{n}\right)^n.
$$

:::

::: {.callout-tip collapse="true"}
## Checking that the probabilities sum to 1


:::

::: {.callout-note collapse="true"}
## The mean (via the definition)

Massage and squint until you recognize the Taylor series of $e^x$:

$$
    \begin{align*}
    E(X)
    &=
\sum\limits_{n=0}^\infty nP(X=n)
    \\
    &=
    \sum\limits_{n=0}^\infty 
    n
    \frac{\lambda^n}{n!}e^{-\lambda}
    \\
    &=
    e^{-\lambda}
    \sum\limits_{n=0}^\infty 
    n
    \frac{\lambda^n}{n!}
    &&
    \text{Pull out constant}
    \\
    &=
    e^{-\lambda}
    \sum\limits_{n=1}^\infty 
    n
    \frac{\lambda^n}{n!}
    &&
    n=0\text{ term is equal to 0}
    \\
    &=
    e^{-\lambda}
    \sum\limits_{n=1}^\infty 
    \frac{\lambda^n}{(n-1)!}
    &&
    n\text{ cancels}
    \\
    &=
    \lambda e^{-\lambda}
    \sum\limits_{n=1}^\infty 
    \frac{\lambda^{n-1}}{(n-1)!}
    &&
    \text{Pull out }\lambda
    \\
    &=
    \lambda e^{-\lambda}
    \sum\limits_{j=0}^\infty 
    \frac{\lambda^{j}}{j!}
    &&
    \text{Reindex}
    \\
    &=
    \lambda e^{-\lambda}
    e^\lambda
    &&
    \text{Recall Taylor series: } e^x=\sum\limits_{k=0}^\infty \frac{x^k}{k!}\,\forall\,x\in\mathbb{R}
    \\
    &=
    \lambda
    .
\end{align*}
$$
:::
